# Generated by Django 5.2.15 on 2026-07-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='rent_amount',
            new_name='price',
        ),
        migrations.AddField(
            model_name='property',
            name='listing_purpose',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], default='Rent', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Pending', 'Pending'), ('Rented', 'Rented'), ('Sold', 'Sold'), ('Expired', 'Expired'), ('Suspended', 'Suspended')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='rent_frequency',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], max_length=20, null=True),
        ),
    ]
